### ISSUE TITLE
Python error with beta19 and DS-KH6320-WTE1 with DS-KV6113-WPE1

### ISSUE THREAD

**Issue by MrNorm** [pergolafabio/Hikvision-Addons#110]
### What happened?

Great addon! It's really added value to the Hikvision doorbell at our property

I noticed that my indoor and outdoor units are no longer showing as connected via MQTT on Home Assistant.

I decided to pull the logs for the Docker container and found a python error (inc below) along with `KeyError: '0 is not registered'` 

My units are DS-KH6320-WTE1 with DS-KV6113-WPE1

Am I doing something wrong here?

Thanks

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.0-beta.19

### Installation type

Docker container (standalone)

### Relevant log output

```Text
hikvision-doorbell | [2023-05-30 19:42:00.760][INF] Private connect 192.168.3.101:8000 sock=154 this=0xef7919f4 cmd=0x117000 port=36566
hikvision-doorbell | [2023-05-30 19:42:00.763][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
hikvision-doorbell | 2023-05-30 19:42:00.777 | DEBUG    | event:start:227 - Registering callback function using SDK
hikvision-doorbell | 2023-05-30 19:42:00.778 | DEBUG    | doorbell:setup_alarm:80 - Arming the device via SDK
hikvision-doorbell | [2023-05-30 19:42:00.779][INF] Private connect 192.168.3.100:8000 sock=169 this=0xef7919f4 cmd=0x111020 port=52364
hikvision-doorbell | 2023-05-30 19:42:00.817 | DEBUG    | doorbell:setup_alarm:80 - Arming the device via SDK
hikvision-doorbell | [2023-05-30 19:42:00.818][INF] Private connect 192.168.3.101:8000 sock=172 this=0xef791fd8 cmd=0x111020 port=36570
hikvision-doorbell | Exception in callback BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)
hikvision-doorbell | handle: <Handle BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)>
hikvision-doorbell | Traceback (most recent call last):
hikvision-doorbell |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
hikvision-doorbell |     key = self._selector.get_key(fd)
hikvision-doorbell |   File "/usr/local/lib/python3.10/selectors.py", line 193, in get_key
hikvision-doorbell |     raise KeyError("{!r} is not registered".format(fileobj)) from None
hikvision-doorbell | KeyError: '0 is not registered'
hikvision-doorbell |
hikvision-doorbell | During handling of the above exception, another exception occurred:
hikvision-doorbell |
hikvision-doorbell | Traceback (most recent call last):
hikvision-doorbell |   File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
hikvision-doorbell |     self._context.run(self._callback, *self._args)
hikvision-doorbell |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 258, in _add_reader
hikvision-doorbell |     self._selector.register(fd, selectors.EVENT_READ,
hikvision-doorbell |   File "/usr/local/lib/python3.10/selectors.py", line 360, in register
hikvision-doorbell |     self._selector.register(key.fd, poller_events)
hikvision-doorbell | PermissionError: [Errno 1] Operation not permitted
hikvision-doorbell | 2023-05-30 19:42:00.821 | DEBUG    | input:loop_forever:29 - Waiting for input command
hikvision-doorbell | [2023-05-30 19:42:30.859][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:43:00.896][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:43:30.931][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:44:05.976][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:44:35.996][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:45:06.039][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:45:36.070][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:46:06.110][DBG] Alarm chan [0] recv timeout[2]!
hikvision-doorbell | [2023-05-30 19:46:36.139][DBG] Alarm chan [0] recv timeout[2]!
```

### Relevant configuration

```YAML
doorbells:
  - name: "Doorbell Outdoor Unit"
    ip: 192.168.3.100
    username: admin
    password: <removed>
  - name: "Doorbell Indoor Unit"
    ip: 192.168.3.101
    username: admin
    password: <removed>

# Define the following options to enable the Home Assistant REST API integration
# home_assistant:
#   url: http://localhost:8123
#  token: <secret_token>

mqtt:
  host: 192.168.0.254
  port: 1883
  ssl: false
  username: hassio
  password: <removed>

system:
  log_level: DEBUG
  sdk_log_level: DEBUG
```

**Comment by pergolafabio** [comment]
Hmm, not seen that error before, what happens if you only configure 1 device ? The indoor or outdoor?

**Comment by MrNorm** [comment]
I've tried with both configs but same error I'm afraid

```
doorbells:
  - name: "Doorbell Indoor Unit"
    ip: 192.168.3.101
    username: admin
    password: <removed>
mqtt:
  host: 192.168.0.254
  port: 1883
  ssl: false
  username: hassio
  password: <removed>
system:
  log_level: DEBUG
  sdk_log_level: DEBUG
```

```
doorbells:
  - name: "Doorbell Outdoor Unit"
    ip: 192.168.3.100
    username: admin
    password: <removed>
mqtt:
  host: 192.168.0.254
  port: 1883
  ssl: false
  username: hassio
  password: <removed>
system:
  log_level: DEBUG
  sdk_log_level: DEBUG
```

I'm not too familiar with the code. Do you know where that error would be thrown? I could try and trace it back
