### ISSUE TITLE
Request for additions more then one Doorbells

### ISSUE THREAD

**Issue by TolianIPB** [pergolafabio/Hikvision-Addons#111]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hello,

The integration is great! Thank you!

I have two bells and two panels.
Panels are dined together - one main, and the second slave.
Doorbells are different. They are responsible for different doors. Both are configured as the Main Doorbell.
I would very much like the integration to support such a configuration. I will be very grateful.

P.S.
I made a motion detector with scripts, but it looks like a button. I think it would be cool if it was already built in.

```
alias:  Motion
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.hikvision_motion
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.hikvision_motion
        state: unavailable
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.hikvision_motion
        state: unknown
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.podyezd_motion
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: input_boolean.toggle
    data: {}
    target:
      entity_id: input_boolean.podyezd_motion
mode: single
```
