### ISSUE TITLE
My homeassistant is core，Running as a standalone container，but can't working

### ISSUE THREAD

**Issue by fengshutao** [pergolafabio/Hikvision-Addons#158]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

None

### Your feature request

My homeassistant is core，Running as a standalone container，but can't working.I follow the docker.md，but not working.I use openwrt docker.

**Comment by pergolafabio** [comment]
What's not working, show config... Logs...

**Comment by fengshutao** [comment]
root@iStoreOS:/opt/docker/hikvision-doorbell# docker compose up -d
yaml: line 10: did not find expected key
root@iStoreOS:/opt/docker/hikvision-doorbell#

**Comment by pergolafabio** [comment]
and whats is line 10 ? maybe you can try dockerhub? ist easier maybe for you ?

**Comment by fengshutao** [comment]
> and whats is line 10 ? maybe you can try dockerhub? ist easier maybe for you ?

![微信图片_20231026212201](https://github.com/pergolafabio/Hikvision-Addons/assets/69944484/73986a4b-58c9-483a-b672-29e20b2ac684)

**Comment by fengshutao** [comment]
> and whats is line 10 ? maybe you can try dockerhub? ist easier maybe for you ?

I used openwrt docker,not synology dockerhub.

**Comment by pergolafabio** [comment]
Hmm, i wonder if its because of the single ' ' 

can you try like:

`DOORBELLS=[{"name":"DS-KH9510", "ip": "192.168.0.71", "port": 8000, "username": "admin", "password": "Password01"}]`

**Comment by pergolafabio** [comment]
it can also be because of bad spaced and indentations in your yaml
Remove all spaces and comment, make the file as clean as possible

**Comment by pergolafabio** [comment]
i also think the doccker compose file on my githib page is indeed wrong
the stuff below env:  does have 4  spaces, i think it only needs 2

change:

```
    env:
        DOORBELLS: '[{"name":"outdoor", "ip": "192.168.0.10", "username": "admin", "password": "password"},{"name":"indoor", "ip": "192.168.0.11", "username": "admin", "password": "password"}]'
        MQTT__HOST: <hostname_of_broker>
        MQTT__USERNAME: <broker_username>
        MQTT__PASSWORD: <broker_password>
        SYSTEM__LOG_LEVEL: INFO
        SYSTEM__SDK_LOG_LEVEL: NONE
```


into:

```
    env:
      DOORBELLS: '[{"name":"outdoor", "ip": "192.168.0.10", "username": "admin", "password": "password"},{"name":"indoor", "ip": "192.168.0.11", "username": "admin", "password": "password"}]'
      MQTT__HOST: <hostname_of_broker>
      MQTT__USERNAME: <broker_username>
      MQTT__PASSWORD: <broker_password>
      SYSTEM__LOG_LEVEL: INFO
      SYSTEM__SDK_LOG_LEVEL: NONE
```
