### ISSUE TITLE
Standalone docker error

### ISSUE THREAD

**Issue by Sonusss** [pergolafabio/Hikvision-Addons#166]
### What happened?

Looks like having problem with SSL...
I checked and both Libssl and libcrypto have the same path...

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

Latest docker tag (7 days ago)

### Installation type

Docker container (standalone)

### Relevant log output

```Text
✔ Container doorbell  Created                                                                                                                                                           0.5s 
Attaching to doorbell
doorbell  | 2023-11-20 10:58:23.676 | DEBUG    | __main__:main:31 - Importing Hikvision SDK
doorbell  | 2023-11-20 10:58:23.683 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: aarch64
doorbell  | 2023-11-20 10:58:23.683 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-aarch64/libhcnetsdk.so
doorbell  | hpr tls index{3}
doorbell  | 2023-11-20 10:58:23.708 | DEBUG    | __main__:main:35 - Hikvision SDK loaded
doorbell  | 2023-11-20 10:58:23.709 | DEBUG    | sdk.utils:setupSDK:86 - Initializing SDK
doorbell  | loop[2] find 2 mac and 0 ip
doorbell  | 2023-11-20 10:58:23.731 | DEBUG    | sdk.utils:setupSDK:100 - SDK initialized
doorbell  | 2023-11-20 10:58:23.731 | DEBUG    | doorbell:__init__:49 - Setting up doorbell: Outdoor
doorbell  | 2023-11-20 10:58:23.732 | DEBUG    | doorbell:authenticate:57 - Logging into doorbell
doorbell  | [2023-11-20 10:58:23.730][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/aarch64-linux-gnu/libz.so.1.2.11], hHandleRet[-1449499888]
doorbell  | [2023-11-20 10:58:23.730][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
doorbell  | [2023-11-20 10:58:23.730][INF] The COM:Core ver is 6.1.8.101, 2021_12_10. Async:1.
doorbell  | [2023-11-20 10:58:23.731][INF] This HCNetSDK ver is 6.1.8.101 Ver 2021_12_10.
doorbell  | [2023-11-20 10:58:23.733][INF] Login dev 10.10.3.192:8000.
doorbell  | [2023-11-20 10:58:23.734][INF] dwTotalNum[2048]
doorbell  | [2023-11-20 10:58:23.736][INF] Private connect 10.10.3.192:8000 sock=6 this=0xa9d10234 cmd=0x10000 port=44844
doorbell  | [2023-11-20 10:58:23.736][INF] LogonDev1 in[10.10.3.192:8000]
doorbell  | [2023-11-20 10:58:23.737][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-aarch64/libcrypto.so], hHandleRet[-1446093456]
doorbell  | [2023-11-20 10:58:23.738][ERR] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Failed, Path[/app/lib-aarch64/libssl.so] syserror[115]
doorbell  | [2023-11-20 10:58:23.738][ERR] Load BASE_DLL_SSLEASY failed[syserr: 115]
doorbell  | [2023-11-20 10:58:23.738][ERR] CoreBase_CreateSSLTrans,CSSLTrans::LoadSSLLib
doorbell  | [2023-11-20 10:58:23.738][ERR] CHIKEncrypt::GenerateRSAKey, CoreBase_CreateSSLTrans FAILED, error[157]
doorbell  | [2023-11-20 10:58:23.738][ERR] CRSAKey::CreateRSAKey, GenerateRSAKey Failed
doorbell  | [2023-11-20 10:58:23.738][ERR] CRSAKey::Start, CreateRSAKey Failed
doorbell  | [2023-11-20 10:58:23.738][ERR] CCoreGlobalCtrlBase::GetRSAEncrypt, CRSAKey Start Failed
doorbell  | [2023-11-20 10:58:23.738][ERR] Interim_GenerateRSAKey, GetRSAEncrypt Failed
doorbell  | [2023-11-20 10:58:23.738][ERR] general public key error
doorbell  | 2023-11-20 10:58:23.748 | ERROR    | __main__:<module>:101 - Error while logging into Outdoor: Device operation failed. Error code:29
doorbell  | [2023-11-20 10:58:23.747][ERR] LogonDev1[10.10.3.192]
doorbell  | [2023-11-20 10:58:23.747][ERR] [10.10.3.192:8000]PRO_LoginHikDevice fail[err=29].[0x-0000001,0x-0000001]
doorbell  | [2023-11-20 10:58:23.747][ERR] CMemberMgrBase::AllocIndex2, MemberStart Failed, iIndex[0]
doorbell  | [2023-11-20 10:58:23.779][INF] COM_Logout[-1][1]
doorbell exited with code
```

### Relevant configuration

```YAML
# docker-compose.yml
version: "3.8"

services:
  doorbell:
    image: pergolafabio/hikvision-doorbell:latest
    tty: true # To receive commands on STDIN
    container_name: doorbell
    build:
      args:
        - BUILD_ARCH=arm64
    env_file:
      - development.env


# development.env
# JSON string with the list of doorbells or indoor stations, for all options, have a look at the [docs](https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell/DOCS.md)
DOORBELLS=[{"name":"Outdoor", "ip": "10.10.3.192", "username": "admin", "password": "xxxx"},{"name":"Indoor", "ip": "10.10.3.193", "username": "admin", "password": "xxx"}]

# Connection to MQTT broker
MQTT__HOST=10.10.0.1
MQTT__PORT=1883
MQTT__USERNAME=xxx
MQTT__PASSWORD=xxx

# Help diagnose problems during development
SYSTEM__LOG_LEVEL=DEBUG
SYSTEM__SDK_LOG_LEVEL=DEBUG

# Load C native libraries required by the Hikvision SDK. Use the correct folder depending on you architecture.
LD_LIBRARY_PATH=lib/

# Enable python module to get stacktraces from C native calls in the SDK
PYTHONFAULTHANDLER=true
```

### Anything else?

Running on RPI4 64bits
