### ISSUE TITLE
Standalone version on a LXC docker container

### ISSUE THREAD

**Issue by Tux92** [pergolafabio/Hikvision-Addons#168]
### What happened?

Thank for your wonderful work. I read all docs and I want to try installing this addon on a LXC container running docker that is hosted on a Proxmox server (I have homessasistant core, so no addon).

I precise that I use docker in this way with many other services so I hope that the problem isn't my architecture.

As you can see the configuration is exactly the same on your doc.

Unfortunately when I try to run docker I have always the below message.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

latest

### Installation type

Docker container (standalone)

### Relevant log output

```Text
[+] Running 1/1
 ! doorbell Warning                                                              1.2s 
[+] Building 0.1s (2/2) FINISHED                                       docker:default
 => [doorbell internal] load build definition from Dockerfile                    0.0s
 => => transferring dockerfile: 2B                                               0.0s
 => [doorbell internal] load .dockerignore                                       0.0s
 => => transferring context: 2B                                                  0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3063751369/Dockerfile: no such file or directory
```
```


### Relevant configuration

```YAML
This is my docker-compose.yml file:

version: "3.8"

services:
  doorbell:
    image: ghcr.io/pergolafabio/hikvision-doorbell:latest
    build:
      args:       
        # Change this according to your architecture (so the correct native C libraries are used)
        - BUILD_ARCH=amd64
        # - BUILD_ARCH=aarch64
      context: .
    env_file:
      - development.env
    tty: true   # To read stdin commands
```

and this my development.env in the same directory of docler-compose.yml
```
# JSON string with the list of doorbells or indoor stations, for all options, have a look at the [docs](https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell/DOCS.md)
DOORBELLS=[{"name":"Posto Interno", "ip": "10.0.0.21", "username": "admin", "password": "xxx"},{"name":"Posto Esterno", "ip": "10.0.0.22", "username": "admin", "password": "xxx"}]

# Connection to MQTT broker
MQTT__HOST=10.0.0.18
#MQTT__PORT=1883
MQTT__USERNAME=mqtt-ha
MQTT__PASSWORD=xxx

# Help diagnose problems during development
SYSTEM__LOG_LEVEL=INFO
SYSTEM__SDK_LOG_LEVEL=NONE

# Load C native libraries required by the Hikvision SDK. Use the correct folder depending on you architecture.
LD_LIBRARY_PATH=lib-amd64/
# Or
# LD_LIBRARY_PATH=lib-aarch64/


# Enable python module to get stacktraces from C native calls in the SDK
PYTHONFAULTHANDLER=true
```
```


### Anything else?

_No response_
