### ISSUE TITLE
hassio.addon_stdin removed

### ISSUE THREAD

**Issue by SDEBEUL** [pergolafabio/Hikvision-Addons#21]
First thanks for building this addon!

Hassio.addon_stdin was removed in v10.
https://github.com/hassio-addons/repository/blob/9d08973517f1e7cb2808e79a8518cefad859a463/ssh/CHANGELOG.md

so this example for controlling a relays does not work anymore in HA 
```
    service: hassio.addon_stdin
    data:
      addon: a53439b8_hikvision_sdk
      input: unlock1
```

Any idea on a work around? 
I would think to use the shell_command services.
But i`m not 100% sure on what to run to exec stdin to the container.
