### ISSUE TITLE
The doorbell never connects to HA

### ISSUE THREAD

**Issue by s493321320** [pergolafabio/Hikvision-Addons#233]
### What happened?

My Hikvision Doorbell turns off every time it starts for a while and there is no physical doorbell
<img width="607" alt="微信图片_20241111095434" src="https://github.com/user-attachments/assets/b618a723-45a3-4af2-b28b-4ccf833f8815">

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.18

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
What kind of device do you have?

**Comment by s493321320** [comment]
> 您拥有哪种设备？

DS-K1T673M-RZSZ

**Comment by s493321320** [comment]
> 好的，我稍后会将其添加到列表中，以便您可以测试它...我会及时通知您

Thanks bro

**Comment by pergolafabio** [comment]
i just added beta 71, can you try ?

**Comment by s493321320** [comment]
> i just added beta 71, can you try ?

Nothing other than [Door Relay] can be used

**Comment by s493321320** [comment]
> i just added beta 71, can you try ?

Even when it's in the call state, it shows "Dell"

**Comment by pergolafabio** [comment]
> > I just added beta 71, can you try it
> 
> Even when it's in the call state, it shows "idle"

Yes , that's normal on those devices, they don't provide the call event, there is a callstatus button, you can poll it manually?

**Comment by s493321320** [comment]
> > > 我刚刚添加了 beta 71，您可以试用吗
> > 
> > 
> > 即使处于通话状态，也显示 “idle”
> 
> 是的，这在这些设备上是正常的，它们不提供 call 事件，有一个 callstatus 按钮，你可以手动轮询它吗？

yes，I can.
does beta work with one device?

**Comment by pergolafabio** [comment]
you can add as many devices you want in the config

**Comment by s493321320** [comment]
> you can add as many devices you want in the config

Why can't my "Hikvison Doorbell" connect to two devices, and the second one doesn't work properly?

**Comment by s493321320** [comment]
![Uploading 12334.png…]()
![Uploading QWE.png…]()

**Comment by s493321320** [comment]
![12334](https://github.com/user-attachments/assets/fa145ad7-1126-4840-abae-9e6df6526b6e)
![QWE](https://github.com/user-attachments/assets/fe0d1182-6a68-4972-bf2f-f0f0165ab741)

**Comment by pergolafabio** [comment]
Not sure , what does the log say?

**Comment by s493321320** [comment]
> 不确定，日志是怎么说的？

![微信截图_20241114140103](https://github.com/user-attachments/assets/949ceff4-6434-40d4-868c-2227f46277a1)

**Comment by pergolafabio** [comment]
That looks good, I don't see any error....
Maybe stop addon, delete all the mqtt devices, restart adddon again

**Comment by s493321320** [comment]
> That looks good, I don't see any error.... Maybe stop addon, delete all the mqtt devices, restart adddon again

I feel so strange, I don't know how to express.  Can you log in to my homeassistant?

**Comment by pergolafabio** [comment]
sure, i can have a quick look

**Comment by s493321320** [comment]
> That looks good, I don't see any error.... Maybe stop addon, delete all the mqtt devices, restart adddon again

![第一](https://github.com/user-attachments/assets/e144c565-bac9-49dd-b323-b37c9a8d7c33)
![第二](https://github.com/user-attachments/assets/ca498e20-56a9-4866-985b-7f8769afb821)
![第三](https://github.com/user-attachments/assets/7eee0ec6-9882-4741-be0b-6af311371493)

**Comment by s493321320** [comment]
http://139.9.76.18:10000/

**Comment by pergolafabio** [comment]
ok, user/pass ?

**Comment by s493321320** [comment]
139.9.76.18

**Comment by s493321320** [comment]
139.9.76.18:10000
username:493321320
password:Chen846215

**Comment by s493321320** [comment]
> 好的，用户/通行证 ？

Have you logged in?

**Comment by pergolafabio** [comment]
yes

**Comment by s493321320** [comment]
Please let me know when it's ready

**Comment by pergolafabio** [comment]
ok, deleted and restarted, working now?

**Comment by s493321320** [comment]
![第四](https://github.com/user-attachments/assets/bf5ff8dd-bfee-4582-b028-f1a703a14331)

**Comment by pergolafabio** [comment]
i changed chinese names to device1 and device2 , now its ok ?

**Comment by pergolafabio** [comment]
maybe it has issues with device names? seems ok now

**Comment by s493321320** [comment]
I'll try it right away.

**Comment by pergolafabio** [comment]
ok, i log out, delete all your messages here on github

**Comment by pergolafabio** [comment]
i have a donate on paypal system, its up to you...

https://www.paypal.com/paypalme/pergolafabio

**Comment by s493321320** [comment]
Do you have Alipay

**Comment by pergolafabio** [comment]
no :-)

**Comment by s493321320** [comment]
I'll transfer you a tip tomorrow. I'll set up an account

**Comment by pergolafabio** [comment]
thnx , much appreciated!

**Comment by s493321320** [comment]
Check out your paypal

**Comment by s493321320** [comment]
![Screenshot_2024-11-14-17-45-33-697_com.android.browser.jpg](https://github.com/user-attachments/assets/5c9cdd55-8130-4c16-8e54-597e3c5affef)

**Comment by pergolafabio** [comment]
ty, received!! :-)

**Comment by s493321320** [comment]
> ty, received!! :-)

hey,Bro！ I have a question. I want you to help me set up the automation system. When the doorbell rings, a pop-up window displays a monitoring screen and a button to open the door.
Can you help me? I'm willing to tip more than last time.

**Comment by pergolafabio** [comment]
something like this, first one is an automation when the sensor changes in my case, the second one is the action if you click on the notify event , i use android

```
# Automation for 
- alias: 'Deurbel Hikvision'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ds_kd8003_call_state
      to: 'ringing'
  - service: notify.xxxx
    data:
      title: "Deurbel"
      message: "Er staat iemand aan de deur!"
      data:
        channel: Doorbell
        actions:
          - action:  deur_open
            title: "Open Door!"     
        priority: high
        ttl: 0  
		
		
## Action to use to open door 
- alias: Action Door Open
  initial_state: 'on'
  trigger:
  - event_data:
      action: deur_open
    event_type: mobile_app_notification_action
    platform: event
  action:
	action: switch.turn_on
	target:
	  entity_id: switch.ds_kd8003_door_relay_0
```

The only thing extra you need, is a poll sensor, cause you dont have the ring event right? you need to poll/press the button every xx seconds, that based on the json you can grab the "ringing" status

once you have the polling, you can retrieve the idle/ringing state like below in an autmation

```
  trigger:
  - platform: state
    entity_id: button.ds_kd8003_caller_info
  condition:
  - condition: template    
    value_template: >
      {% if (state_attr("button.ds_kd8003_call_status", "CallStatus")['status']) == "ringing" %}True{% endif %} 
```

you can play with the template editor:

![image](https://github.com/user-attachments/assets/7e15f11c-e955-40ce-831c-ff883edfb48d)
