### ISSUE TITLE
Logbook is showing actions that never occurred

### ISSUE THREAD

**Issue by kujass** [pergolafabio/Hikvision-Addons#258]
### What happened?

I just integrated my DS-KV8213-WME1(B), and I noticed that the logbook is acting a bit strangely. It’s registering new events and status changes every few seconds without any apparent reason. The Door 1 relay and Call State sensor are also changing states unexpectedly.

Aside from that, the doorbell station functions normally. I can answer, hang up, and reject calls, and all of these actions are correctly recorded in the logbook.

<img width="352" alt="Image" src="https://github.com/user-attachments/assets/4f1e6ed2-6071-4043-8a11-98eefa9b5987" />

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.21-amd64

### Installation type

Home Assistant add-on

### Relevant log output

```Text

```

### Relevant configuration

```YAML
Device info: DS-KV8213-WME1(B) by Hikvision
Firmware: V2.2.53
Hardware: 0x0

Integration type: MQTT
Installation type": Home Assistant Container (version 2025.3.4)
```
